name: Plugin release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.x
            - name: npm build
              run: |
                  npm install
                  npm run build --if-present
            - name: Create zip archive
              run: |
                  zip -j templater-obsidian.zip main.js manifest.json styles.css
            - name: Create Release
              # https://github.com/ncipollo/release-action
              uses: ncipollo/release-action@v1.7.3
              with:
                  artifacts: "main.js,manifest.json,styles.css,templater-obsidian.zip"
                  token: ${{ secrets.GITHUB_TOKEN }}
